services:
  redis:
    image: redis:7-alpine
    container_name: poc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  api:
    build: .
    container_name: poc-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
    volumes:
      - .:/app
      - /app/.venv  # Exclude venv from mount
    restart: unless-stopped
    command: uvicorn interface.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  redis_data:
