version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: poc-postgres
    environment:
      POSTGRES_DB: intelligent_document_search
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - poc-network

  redis:
    image: redis:7-alpine
    container_name: poc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - poc-network

volumes:
  postgres_data:
  redis_data:

networks:
  poc-network:
    driver: bridge